# fly.toml app configuration file generated for hackathorion-api on 2025-05-17T01:34:36-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hackathorion-api'
primary_region = 'gru'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
